// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// decision_making_cpp
Rcpp::DataFrame decision_making_cpp(std::string mode, std::string policy, Rcpp::DataFrame data, Rcpp::CharacterVector options, int seed, std::string sub_choose, std::string rob_choose, std::string L_choice, std::string R_choice, std::string L_reward, std::string R_reward, std::string var1, std::string var2, double initial_value, int threshold, double lapse, Rcpp::NumericVector gamma, Rcpp::NumericVector eta, Rcpp::NumericVector epsilon, Rcpp::NumericVector lambda, Rcpp::NumericVector pi, Rcpp::NumericVector tau, Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::Function util_func, Rcpp::Function rate_func, Rcpp::Function expl_func, Rcpp::Function bias_func, Rcpp::Function prob_func);
RcppExport SEXP _binaryRL_decision_making_cpp(SEXP modeSEXP, SEXP policySEXP, SEXP dataSEXP, SEXP optionsSEXP, SEXP seedSEXP, SEXP sub_chooseSEXP, SEXP rob_chooseSEXP, SEXP L_choiceSEXP, SEXP R_choiceSEXP, SEXP L_rewardSEXP, SEXP R_rewardSEXP, SEXP var1SEXP, SEXP var2SEXP, SEXP initial_valueSEXP, SEXP thresholdSEXP, SEXP lapseSEXP, SEXP gammaSEXP, SEXP etaSEXP, SEXP epsilonSEXP, SEXP lambdaSEXP, SEXP piSEXP, SEXP tauSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP util_funcSEXP, SEXP rate_funcSEXP, SEXP expl_funcSEXP, SEXP bias_funcSEXP, SEXP prob_funcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< std::string >::type policy(policySEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type options(optionsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< std::string >::type sub_choose(sub_chooseSEXP);
    Rcpp::traits::input_parameter< std::string >::type rob_choose(rob_chooseSEXP);
    Rcpp::traits::input_parameter< std::string >::type L_choice(L_choiceSEXP);
    Rcpp::traits::input_parameter< std::string >::type R_choice(R_choiceSEXP);
    Rcpp::traits::input_parameter< std::string >::type L_reward(L_rewardSEXP);
    Rcpp::traits::input_parameter< std::string >::type R_reward(R_rewardSEXP);
    Rcpp::traits::input_parameter< std::string >::type var1(var1SEXP);
    Rcpp::traits::input_parameter< std::string >::type var2(var2SEXP);
    Rcpp::traits::input_parameter< double >::type initial_value(initial_valueSEXP);
    Rcpp::traits::input_parameter< int >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type lapse(lapseSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type util_func(util_funcSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type rate_func(rate_funcSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type expl_func(expl_funcSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type bias_func(bias_funcSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type prob_func(prob_funcSEXP);
    rcpp_result_gen = Rcpp::wrap(decision_making_cpp(mode, policy, data, options, seed, sub_choose, rob_choose, L_choice, R_choice, L_reward, R_reward, var1, var2, initial_value, threshold, lapse, gamma, eta, epsilon, lambda, pi, tau, alpha, beta, util_func, rate_func, expl_func, bias_func, prob_func));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_binaryRL_decision_making_cpp", (DL_FUNC) &_binaryRL_decision_making_cpp, 29},
    {NULL, NULL, 0}
};

RcppExport void R_init_binaryRL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
