#' Title
#'
#' @param data a list resulting from the 'step7' process of the `output` function. 
#' 
#' @param back Whether to convert to the original data format. 
#' default: `back = FALSE`
#' 
#' @param sub_choose A string specifying the name of the column that represents the choice made by the subject. 
#' Provide the name of the column as a character string 
#' e.g., `sub_choose = "Choose"`
#' 
#' @param rob_choose A string specifying the name of the column that represents the choice made by the robot[model] 
#' a default column generated by `binaryRL`
#' default., `rob_choose = "Rob_Choose"`
#' 
#' @param raw_cols All column's name in your raw data
#'
#' @returns binaryRL[list]:
#'   \itemize{
#'     \item{\code{data}: new raw data (decision made by robot)}
#'     \item{\code{params}: all parameters value}
#'     \item{\code{numeric}: ACC}
#'     \item{\code{numeric}: LogL}
#'     \item{\code{numeric}: AIC}
#'     \item{\code{numeric}: BIC}
#'   }
#' @export
#'
back <- function(
  data, 
  back = FALSE,
  sub_choose = "Sub_Choose",
  rob_choose = "Rob_Choose",
  raw_cols = c(
    "Subject", "Block", "Trial",
    "L_choice", "R_choice", "L_reward", "R_reward",
    "Sub_Choose"
  )
){
  if (back == TRUE){
    data[[1]][[sub_choose]] <- data[[1]][[rob_choose]]
    data[[1]] <- data[[1]][, raw_cols]
  } else {
    data <- data
  }
  
  return(data)
}
