#' simulate_l
#' 
#' @description
#' 
#' This function generates simulated datasets using a
#' user-defined objective function. You can specify the number of
#' iterations to control how many datasets are generated.
#' These datasets can be used for parameter recovery and model
#' recovery. 
#' For more information, please refer to the GitHub repository:
#' https://github.com/yuki-961004/binaryRL
#'  
#' @param obj_func [function] a function with only ONE argument `params`. 
#'  Additionally, it is important to note that the data needs to be retrieved 
#'  from parent.frame(). This function returns the binaryRL_res(res).
#' 
#' @param n_params [integer] number of free parameters
#' 
#' @param lower [vector] lower bounds of free parameters
#' 
#' @param upper [vector] upper bounds of free parameters
#' 
#' @param seed [integer] random seed. This ensures that the results are 
#'  reproducible and remain the same each time the function is run. 
#'  default: `seed = 123`
#'  
#' @param iteration [integer] iteration
#'
#' @returns a list with fake data generated by random free parameters
#' @export
#'
simulate_l <- function(
  obj_func, 
  n_params, 
  lower, 
  upper,
  iteration = 10,
  seed = 123
) {
  list_simulated <- list()
  
  for (i in 1:iteration) {
    params <- c()
    
    for (j in 1:n_params) {
      set.seed(seed + n_params * i + j) # 确保每次迭代种子都不同
      params[j] <- runif(n = 1, min = lower[j], max = upper[j])
    }
    
    list_simulated[[i]] <- obj_func(params = params)
    list_simulated[[i]]$input <- params
  }
  
  return(list_simulated)
}
