# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decision_making_cpp <- function(mode, policy, data, options, seed, sub_choose, rob_choose, L_choice, R_choice, L_reward, R_reward, var1, var2, initial_value, threshold, lapse, gamma, eta, epsilon, lambda, pi, tau, alpha, beta, util_func, rate_func, expl_func, bias_func, prob_func) {
    .Call(`_binaryRL_decision_making_cpp`, mode, policy, data, options, seed, sub_choose, rob_choose, L_choice, R_choice, L_reward, R_reward, var1, var2, initial_value, threshold, lapse, gamma, eta, epsilon, lambda, pi, tau, alpha, beta, util_func, rate_func, expl_func, bias_func, prob_func)
}

