#' @title 
#' Step 3: Optimizing parameters to fit real data
#' 
#' @description
#' This function is designed to fit the optimal parameters of black-box
#'  functions (models) to real-world data. Provided that the black-box
#'  function adheres to the specified interface
#'  (demo:  
#'     \code{\link[binaryRL]{TD}}, 
#'     \code{\link[binaryRL]{RSTD}}, 
#'     \code{\link[binaryRL]{Utility}}
#'  )
#'  , this function can employ the various optimization algorithms detailed 
#'  below to find the best- fitting parameters for your model.
#'  
#'  The function provides several optimization algorithms:
#'   \itemize{
#'     \item 1. L-BFGS-B (from \code{stats::optim})
#'     \item 2. Simulated Annealing (\code{GenSA::GenSA})
#'     \item 3. Genetic Algorithm (\code{GA::ga})
#'     \item 4. Differential Evolution (\code{DEoptim::DEoptim})
#'     \item 5. Particle Swarm Optimization (\code{pso::psoptim})
#'     \item 6. Bayesian Optimization (\code{mlrMBO::mbo})
#'     \item 7. Covariance Matrix Adapting Evolutionary Strategy (\code{cmaes::cma_es})
#'     \item 8. Nonlinear Optimization (\code{nloptr::nloptr})
#'   }
#' 
#'  For more information, please refer to the homepage of this package:
#'  \url{https://yuki-961004.github.io/binaryRL/}
#'  
#' @note
#' The primary difference between `fit_p` and `rcv_d` lies in their data
#'  source: `fit_p` fits parameters to real data, while `rcv_d` fits
#'  parameters to synthetic data generated by models. Many studies
#'  inappropriately skip the `rcv_d` step.
#'
#' Imagine `fit_p` as the actual boxing match, and `rcv_d` as the weigh-in.
#'  Boxers of different weight classes shouldn't compete directly.
#'  
#' Similarly, if a competing model lacks the ability of parameter or model
#'  recovering, even if your proposed model outperforms it in `fit_p`,
#'  it doesn't necessarily make your proposed model a good one.
#'  
#' @param policy [character]
#' Specifies the learning policy to be used.
#' This determines how the model updates action values based on observed or
#'   simulated choices. It can be either \code{"off"} or \code{"on"}.
#'   
#' \itemize{
#'   \item \strong{Off-Policy}: \strong{Q-learning}
#'    This is the most common approach for modeling
#'     reinforcement learning in Two-Alternative Forced Choice (TAFC) tasks.
#'     In this mode, the model's goal is to learn the underlying value of
#'     each option by observing the human participant's behavior. It achieves
#'     this by consistently updating the value of the option that the
#'     human actually chose. The focus is on understanding the value 
#'     representation that likely drove the participant's decisions.
#'
#'   \item \item \strong{Off-Policy}: \strong{SARSA} 
#'    In this mode, the target policy and the behavior policy are identical. 
#'     The model first computes the selection probability for each option based 
#'     on their current values. Critically, it then uses these probabilities to 
#'     sample its own action. The value update is then performed on the action 
#'     that the model itself selected. This approach focuses more on directly 
#'     mimicking the stochastic choice patterns of the agent, rather than just 
#'     learning the underlying values from a fixed sequence of actions.
#' }
#'  
#' @param estimate [character] 
#'  Estimation method. Default is \code{"MLE"}, 
#'   meaning the algorithm will iterate to find the parameter values that 
#'   maximize the likelihood, without considering any prior information. If 
#'   \code{estimate = "MAP"}, prior distributions must be specified via the 
#'   \code{priors} argument. After an initial optimization using likelihood, 
#'   the algorithm estimates the distribution of each parameter across all 
#'   subjects, fits a normal or exponential prior, and re-optimizes to maximize 
#'   the posterior. This procedure iterates until convergence and follows the 
#'   EM (Expectation-Maximization) framework.
#'  
#' @param data [data.frame] 
#' This data should include the following mandatory columns: 
#'  \itemize{
#'    \item \code{sub} "Subject"
#'    \item \code{time_line} "Block" "Trial"
#'    \item \code{L_choice} "L_choice"
#'    \item \code{R_choice} "R_choice"
#'    \item \code{L_reward} "L_reward"
#'    \item \code{R_reward} "R_reward"
#'    \item \code{sub_choose} "Sub_Choose"
#'  }
#'  
#' @param id [vector]
#' Specifies the subject ID(s) for whom optimal parameters are to be fitted.
#'  If you intend to fit all subjects within your dataset, it is strongly
#'  recommended to use \code{id = unique(data$Subject)}. This approach accounts
#'  for cases where subject IDs in the dataset may not be simple numeric
#'  sequences (e.g., "1", "2", "3", "4") or may contain string
#'  entries (e.g., "1", "2", "3", "004"). Using \code{id = 1:4} could lead to 
#'  errors if IDs are not sequentially numbered integers.
#'  
#'  \code{default: id = NULL}
#'  
#' @param n_trials [integer]
#' Represents the total number of trials a single subject experienced
#'  in the experiment. If this parameter is kept at its default value
#'  of `NULL`, the program will automatically detect how many trials
#'  a subject experienced from the provided data. This information
#'  is primarily used for calculating model fit statistics such as
#'  AIC (Akaike Information Criterion) and BIC (Bayesian Information
#'  Criterion).
#'  
#'  \code{default: n_trials = NULL}
#' 
#' @param funcs [character]
#' A character vector containing the names of all user-defined functions
#'  required for the computation. When parallel computation is enabled
#'  (i.e., `nc > 1`), user-defined models and their custom functions might
#'  not be automatically accessible within the parallel environment.
#'
#' Therefore, if you have created your own reinforcement learning model
#'  that modifies the package's default six default functions 
#'  (default functions: 
#'     \code{util_func = \link[binaryRL]{func_gamma}}, 
#'     \code{rate_func = \link[binaryRL]{func_eta}}, 
#'     \code{expl_func = \link[binaryRL]{func_epsilon}},
#'     \code{bias_func = \link[binaryRL]{func_pi}},
#'     \code{prob_func = \link[binaryRL]{func_tau}},
#'     \code{loss_func = \link[binaryRL]{func_logl}}
#'  ), 
#'  you must explicitly provide the names of your custom functions as a 
#'  vector here.
#' 
#' @param model_name [list] 
#' The name of fit modals
#' 
#' @param fit_model [list] 
#' A collection of functions applied to fit models to the data.
#' 
#' @param lower [list] 
#' The lower bounds for model fit models
#' 
#' @param upper [list] 
#' The upper bounds for model fit models
#' 
#' @param priors [list] A \code{list} object for specifying the Bayesian prior
#'   distributions for each model parameter. Each element in the list
#'   should be named after a parameter and contain a function that returns the 
#'   log probability density.
#'   
#'   By default, a set of priors is used. For most parameters, this is a
#'   \strong{Uniform(0, 1)} distribution, which acts as an uninformative prior.
#'   This means that for these parameters, the Maximum A Posteriori (MAP)
#'   estimate will be identical to the Maximum Likelihood Estimate (MLE).
#'
#'   The exception is for the inverse temperature parameter associated with the
#'   softmax function (\code{tau}). This parameter uses an 
#'   \strong{Exponential(1)} distribution as its prior. This is a weakly
#'   informative prior that regularizes the model by favoring smaller,
#'   positive values, thus preventing extremely large parameter estimates.
#' 
#' @param tolerance [numeric] 
#' Convergence threshold for MAP estimation. If the change in
#'  log posterior probability between iterations is smaller than this value, the
#'  algorithm is considered to have converged and the program will stop.
#' 
#' @param initial_params [vector]
#' Initial values for the free parameters that the optimization algorithm will
#'  search from. These are primarily relevant when using algorithms that require
#'  an explicit starting point, such as \code{L-BFGS-B}. If not specified,
#'  the function will automatically generate initial values close to zero.
#'  
#'  \code{default: initial_params = NA}.
#'
#' @param initial_size [integer]
#' This parameter corresponds to the \strong{population size} in genetic 
#'  algorithms (\code{GA}). It specifies the number of initial candidate
#'  solutions that the algorithm starts with for its evolutionary search.
#'  This parameter is only required for optimization algorithms that operate on
#'  a population, such as \code{GA} or \code{DEoptim}. 
#'  
#'  \code{default: initial_size = 50}.
#'  
#' @param iteration_i [integer] 
#' The number of iterations the optimization algorithm will perform
#'  when searching for the best-fitting parameters during the fitting
#'  phase. A higher number of iterations may increase the likelihood of 
#'  finding a global optimum but also increases computation time.
#'  
#' @param iteration_g [integer]
#' The maximum number of iterations for the Expectation-Maximization (EM)
#'  based MAP estimation. The algorithm will stop once this iteration
#'  count is reached, even if the change in the log-posterior value has
#'  not yet fallen below the `tolerance` threshold.
#' 
#' @param seed [integer] 
#' Random seed. This ensures that the results are 
#'  reproducible and remain the same each time the function is run. 
#'  
#'  \code{default: seed = 123}
#'  
#' @param nc [integer]
#' Number of cores to use for parallel processing. Since fitting
#' optimal parameters for each subject is an independent task,
#' parallel computation can significantly speed up the fitting process:
#' \itemize{
#'   \item \strong{nc = 1}: The fitting proceeds sequentially.
#'   Parameters for one subject are fitted completely before moving
#'   to the next subject.
#'   \item \strong{nc > 1}: The fitting is performed in parallel
#'   across subjects. For example, if \code{nc = 4}, the algorithm will
#'   simultaneously fit data for four subjects. Once these are complete,
#'   it will proceed to fit the next batch of subjects (e.g., subjects
#'   5-8), and so on, until all subjects are processed.
#' }
#' 
#'  \code{default: nc = 1}
#'  
#' @param algorithm [character] 
#' Choose an algorithm package from
#'  \code{L-BFGS-B}, \code{GenSA},\code{GA},\code{DEoptim},\code{PSO},
#'  \code{Bayesian}, \code{CMA-ES}.
#'  
#' In addition, any algorithm from the \code{nloptr} package is also
#'  supported. If your chosen \code{nloptr} algorithm requires a local search,
#'  you need to input a character vector. The first element represents
#'  the algorithm used for global search, and the second element represents
#'  the algorithm used for local search.
#'
#' @returns 
#' The optimal parameters found by the algorithm for each subject,
#'  along with the model fit calculated using these parameters.
#'  This is returned as an object of class \code{binaryRL} containing results
#'  for all subjects with all models.
#'  
#' @examples
#' \dontrun{
#' comparison <- binaryRL::fit_p(
#'   data = binaryRL::Mason_2024_Exp2,
#'   id = unique(binaryRL::Mason_2024_Exp2$Subject),
#' #+-----------------------------------------------------------------------------+#
#' #|----------------------------- black-box function ----------------------------|#
#'   #funcs = c("your_funcs"),
#'   policy = c("off", "on"),
#'   fit_model = list(binaryRL::TD, binaryRL::RSTD, binaryRL::Utility),
#'   model_name = c("TD", "RSTD", "Utility"),
#' #|--------------------------------- estimate ----------------------------------|#
#'   estimate = c("MLE", "MAP"),
#' #|------------------------------------ MLE ------------------------------------|#
#'   lower = list(c(0, 0), c(0, 0, 0), c(0, 0, 0)),
#'   upper = list(c(1, 10), c(1, 1, 10), c(1, 1, 10)),
#' #|------------------------------------ MAP ------------------------------------|#
#'   priors = list(
#'     list(
#'       eta = function(x) {stats::dunif(x, min = 0, max = 1, log = TRUE)}, 
#'       tau = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
#'     ), 
#'     list(
#'       eta = function(x) {stats::dunif(x, min = 0, max = 1, log = TRUE)}, 
#'       eta = function(x) {stats::dunif(x, min = 0, max = 1, log = TRUE)}, 
#'       tau = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
#'     ), 
#'     list(
#'       eta = function(x) {stats::dunif(x, min = 0, max = 1, log = TRUE)}, 
#'       gamma = function(x) {stats::dunif(x, min = 0, max = 1, log = TRUE)}, 
#'       tau = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
#'     )
#'   ),
#' #|----------------------------- iteration number ------------------------------|#
#'   iteration_i = 10,
#'   iteration_g = 10,
#' #|-------------------------------- algorithms ---------------------------------|#
#'   nc = 1,                 # <nc > 1>: parallel computation across subjects
#'   # Base R Optimization
#'   algorithm = "L-BFGS-B"  # Gradient-Based (stats)
#' #|-----------------------------------------------------------------------------|#
#'   # Specialized External Optimization
#'   #algorithm = "GenSA"    # Simulated Annealing (GenSA)
#'   #algorithm = "GA"       # Genetic Algorithm (GA)
#'   #algorithm = "DEoptim"  # Differential Evolution (DEoptim)
#'   #algorithm = "PSO"      # Particle Swarm Optimization (pso)
#'   #algorithm = "Bayesian" # Bayesian Optimization (mlrMBO)
#'   #algorithm = "CMA-ES"   # Covariance Matrix Adapting (cmaes)
#' #|-----------------------------------------------------------------------------|#
#'   # Optimization Library (nloptr)
#'   #algorithm = c("NLOPT_GN_MLSL", "NLOPT_LN_BOBYQA")
#' #|-------------------------------- algorithms ---------------------------------|#
#' #################################################################################
#' )
#'
#' result <- dplyr::bind_rows(comparison)
#'
#' # Ensure the output directory exists before writing
#' if (!dir.exists("../OUTPUT")) {
#'   dir.create("../OUTPUT", recursive = TRUE)
#' }
#' 
#' write.csv(result, "../OUTPUT/result_comparison.csv", row.names = FALSE)
#' }
#' 
fit_p <- function(
  policy = c("off", "on"),
  estimate = c("MLE", "MAP"),  
  
  data,
  id = NULL,
  n_trials = NULL,
  
  funcs = NULL,
  model_name = c("TD", "RSTD", "Utility"),
  fit_model = list(binaryRL::TD, binaryRL::RSTD, binaryRL::Utility),
  lower = list(c(0, 0), c(0, 0, 0), c(0, 0, 0)),
  upper = list(c(1, 1), c(1, 1, 1), c(1, 1, 1)),
  
  priors = NULL,
  tolerance = 0.001,
  
  iteration_i = 10,
  iteration_g = 10,
  
  initial_params = NA,
  initial_size = 50,
  seed = 123,
  
  nc = 1,
  algorithm
){
################################# [ info ] #####################################   
  
  # 事前准备. 探测信息
  info <- suppressWarnings(suppressMessages(detect_information(data = data)))
  
  if (is.null(n_trials)) {
    n_trials <- info[["n_trials"]]
  }
  
  if (is.null(id)) {
    id <- info[["all_ids"]]
  }
  
  # 创建空list用于储存结果
  model_comparison <- list()
  model_result <- list()

################################ [ threads ] ###################################  
  
  # 单线程还是多线程
  if (nc == 1) {
    future::plan(future::sequential)
  }
  # 是多线程, 且是Windows系统
  else if (nc >= 1 & base::.Platform$OS.type == "windows") {
    future::plan(future::multisession, workers = nc)
  } 
  # 是多线程, 且不是Windows系统, macOS和Linux
  else if (nc >= 1 & base::.Platform$OS.type != "windows") { 
    future::plan(future::multicore, workers = nc)
  }
  else {
    stop("Something went wrong with parallel computation setup.")
  }
  
  doFuture::registerDoFuture()

############################# [ for loop models] ###############################
    
  # 每个model都使用初始的priors
  params_priors <- list()
  
  for (i in 1:length(fit_model)){
    
    message(paste0(
      "\n", 
      "Fitting Model: ", model_name[i], 
      "\n"
    ))
    
    n_subjects <- length(id)
    n_params <- length(lower[[i]])

########################### [ foreach loop subs ] ##############################    
    
    # 进度条
    progressr::handlers(progressr::handler_txtprogressbar)
    
    progressr::with_progress({
      
      # 进度条与此时运行的被试数绑定
      p <- progressr::progressor(steps = n_subjects)
      
      # doRNG保证种子不变
      doRNG::registerDoRNG(seed = seed)
      
      # 初始化(定义)foreach中的j
      j <- NA

################################# [ MLE ] ######################################
      
      # 抑制每个线程加载包时的信息
      suppressMessages({
        model_result <- foreach::foreach(
          j = 1:n_subjects, .combine = rbind,
          .packages = c("binaryRL"),
          .export = funcs
        ) %dorng% {

          binaryRL_res <- binaryRL::optimize_para(
            policy = policy,
            estimate = estimate,
            
            data = data,
            id = id[j],
            n_trials = n_trials,
            n_params = n_params,
            
            obj_func = fit_model[[i]],
            lower = lower[[i]],
            upper = upper[[i]],
            priors = priors[[i]],
            
            initial_params = initial_params,
            initial_size = initial_size,
            
            iteration = iteration_i,
            seed = seed,
            algorithm = algorithm
          )
          
          result_j <- data.frame(
            fit_model = model_name[i],
            Subject = id[j],
            ACC = binaryRL_res$acc,
            LogL = -binaryRL_res$ll,
            LogPr = -binaryRL_res$lpr,
            LogPo = -binaryRL_res$lpo,
            AIC = binaryRL_res$aic,
            BIC = binaryRL_res$bic
          )
          
          for (k in 1:n_params) {
            result_j[1, k + 8] <- binaryRL_res$output[k]
            names(result_j)[k + 8] <- paste0("param_", k)
          }
          
          # 在foreach循环内更新进度条
          p() 
          return(result_j)
        }
      })
    })

################################# [ MAP ] ######################################
        
    # Expectation-Maximization Algorithm
    if (estimate == "MAP") {
      
      message("Starting Expectation-Maximization Algorithm")
      
      # 基于上面第一次的结果更新先验概率
      params_priors[[i]] <- update_priors(
        model_result = model_result,
        priors = priors[[i]], 
        n_params = n_params,
        param_prefix = "param_"
      )
      
      # 因为之后使用while循环
      # 设定初始后验差值, 永远比tolerance大1, 保证一定会运行一次
      delta_LogPo <- tolerance + 1
      # 计算第一次拟合时的似然后验值
      LogPo <- sum(model_result$LogPo)
      
      message(
        paste0(
          "Log-Posterior Probability: ", round(LogPo, 2)
        )
      )
      
      # 初始化后验迭代次数
      iteration <- 0
      
      while (abs(delta_LogPo) > tolerance) {
        
        # 进度条
        progressr::handlers(progressr::handler_txtprogressbar)
        
        progressr::with_progress({
          
          # 进度条与此时运行的被试数绑定
          p <- progressr::progressor(steps = n_subjects)
          
          # doRNG保证种子不变
          doRNG::registerDoRNG(seed = seed)
          
          # 初始化(定义)foreach中的j (无意义, 仅为通过R CMD check)
          j <- NA
          
          # 抑制每个线程加载包时的信息
          suppressMessages({
            model_result <- foreach::foreach(
              j = 1:n_subjects, .combine = rbind,
              .packages = c("binaryRL"),
              .export = funcs
            ) %dorng% {
              
              binaryRL_res <- binaryRL::optimize_para(
                policy = policy,
                estimate = estimate,
                
                data = data,
                id = id[j],
                n_trials = n_trials,
                n_params = n_params,
                
                obj_func = fit_model[[i]],
                lower = lower[[i]],
                upper = upper[[i]],
                priors = params_priors[[i]],
                
                initial_params = initial_params,
                initial_size = initial_size,
                
                iteration = iteration_i,
                seed = seed,
                algorithm = algorithm
              )
              
              result_j <- data.frame(
                fit_model = model_name[i],
                Subject = id[j],
                ACC = binaryRL_res$acc,
                LogL = -binaryRL_res$ll,
                LogPr = -binaryRL_res$lpr,
                LogPo = -binaryRL_res$lpo,
                AIC = binaryRL_res$aic,
                BIC = binaryRL_res$bic
              )
              
              for (k in 1:n_params) {
                result_j[1, k + 8] <- binaryRL_res$output[k]
                names(result_j)[k + 8] <- paste0("param_", k)
              }
              
              # 在foreach循环内更新进度条
              p() 
              return(result_j)
            }
          })
        })
        
        # 计算此时的似然后验变化量
        delta_LogPo <- sum(model_result$LogPo) - LogPo
        
        # 更新似然后验
        LogPo <- sum(model_result$LogPo)
        
        message(
          paste0(
            "Log-Posterior Probability: ", round(LogPo, 2),
            ", ",
            "\u0394: ", sign_numbers(delta_LogPo), round(delta_LogPo, 2)
          )
        )
        
        # 修改先验分布
        params_priors[[i]] <- update_priors(
          model_result = model_result,
          priors = params_priors[[i]], 
          n_params = n_params,
          param_prefix = "param_"
        )
        
        # EM也不会无限制跑下去
        iteration <- iteration + 1
        if (iteration >= iteration_g) {
          break 
        }
      }
    }
    
    # 每次将一个模型的结果输出, 然后跑下一个模型的拟合
    model_comparison[[i]] <- model_result
  }
  
  # 取消注册的线程
  future::plan(future::sequential)
  
  result <- model_comparison
  
  return(result)
}